In [4]:
import numpy as np

In [20]:
mylist= [1,2,3]
print(mylist) #list is a set 

[1, 2, 3]


In [21]:
new_array=np.array(mylist)
print(new_array) #numpy array is a matrix 

[1 2 3]


In [14]:
np.arange(0,10,2) ##等差数列

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(5) ##create zeros, one can also do np.ones(x)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,5)) #2 rows and 5 cols 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
np.linspace(0,10,5) # from 0 to 10, linearly spaced 3 numbers. Including end point here.  

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.eye(5) #identity(square) matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5,2) #Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.

array([[0.68867581, 0.3878053 ],
       [0.59054251, 0.58666159],
       [0.79546301, 0.02807668],
       [0.39291006, 0.73740915],
       [0.16858067, 0.83359095]])

In [31]:
np.random.randn(3,2) #returning samples from a mean=0, normal distribution 

array([[-0.52399285, -1.15781656],
       [ 1.40672147,  0.19254088],
       [-0.96661873, -0.18944205]])

In [35]:
np.random.randint(2,10,(2,2)) #random integers 

array([[7, 5],
       [9, 6]])

In [37]:
np.random.seed(42) #set a seed, set a random-state, so one can repreduce the random list 
np.random.rand(4) #make sure do in the same cell 

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [70]:
arr = np.arange(0,25)

In [71]:
arr.reshape(5,5) #take the same number from arr and reformat it 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr = np.random.randint(0,101,10)

In [51]:
ranarr.max() #for example, list does not support max()

99

In [52]:
ranarr.argmax() #the index number of max 

5

In [53]:
ranarr.dtype #type

dtype('int64')

In [72]:
arr.shape #(25,) 

(25,)

In [73]:
arr_2 = arr.reshape(5,5)

In [74]:
arr_2.shape

(5, 5)

In [75]:
arr_3= arr.reshape(25,1)

In [76]:
arr_3.shape

(25, 1)