In [1]:
import numpy as np

In [2]:
arr =np.arange(0,10)

In [3]:
arr + 5 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
arr.mean()

4.5

In [10]:
arr.std()

2.8722813232690143

In [11]:
arr.var()

8.25

In [14]:
arr2d=np.arange(0,25).reshape(5,5)

In [15]:
arr2d.shape

(5, 5)

In [16]:
arr2d.sum()

300

In [17]:
arr2d.sum(axis=0) #axis=0, perform the operation across the 0 index of the shape(row), sum up all numbers in the same col. 

array([50, 55, 60, 65, 70])

In [18]:
arr2d.sum(axis=1)#axis=1, perform the operation across the 1 index of the shape(col), sum up all numbers in the same row.

array([ 10,  35,  60,  85, 110])

In [19]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [20]:
account_transactions.sum()

2720