In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr[:5] #from start 

array([0, 1, 2, 3, 4])

In [5]:
arr[5:]#from end 

array([ 5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]=100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
slice_of_arr=arr[0:5]

In [10]:
slice_of_arr[:]=99 #broadcasting operation has affected the original array 

In [12]:
arr_copy=arr.copy() #otherwise need to copy the original array 

In [13]:
arr_copy[:]=100

In [15]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d.shape

(3, 3)

In [33]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr[0:5]=np.arange(0,5)

In [38]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [39]:
bool_arr = arr >4 

In [40]:
arr[bool_arr] #only return index when bool_arr is true 

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [46]:
dice_rolls>2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])